### ISSUE TITLE
SkillName Not Populating

### ISSUE THREAD

**Issue by jmferris** [devatwork/LinkedINSharp#1]
The SkillName is not populating, when included as a ProfileField.  The string value for the Name property always returns as null.

To Reproduce:

Add a ProfileField("skills") to the field list on a request.

The Result:

While the skill's ID is populated, name is not.

Cause:

This is due to a serialization issue.  The name of the SkillName property on Skill needs to be "Skill" to match the XML response.  The property cannot simply be renamed to Skill, though, as the Skill class will need to be renamed, as a member in a class cannot have the same name as the class itself.  As a local and temporary workaround, I have renamed the "Skill" class to "Skills" and renamed the "Name" property in the now-renamed "Skills" class to "Skill".  After the change, SkillName is correctly populated, as per the model definition.

**Comment by devatwork** [comment]
Thanks for reporting, the workaround you describe sounds reasonable to me. Could you send me a pull-request?

**Comment by jmferris** [comment]
Changes made and pull request created.  Thank you!
